### ISSUE TITLE
About training on other datasets

### ISSUE THREAD

**Issue by Mesks** [5ofwind/RDVR#4]
Hello, thank you very much for providing the open source code. I tested the RDVR-H.265 pre-trained model on my data set, which is very close to the MSSSM-BPP curve provided in your paper, which can prove the generalization ability of your model, but we still need to retrain or fine-tune it on my data set (mine is far from natural video). However, it seems that only vimeo90k's data set is supported in the training code, so I would like to ask you how to train on my data set.

Currently, I set all the training video frames (at the same resolution) in one folder and use data_script/create_lmdb.py "general" mode to generate a .lmdb-suffix folder (containing two mdb files and one pkl file), as well as val video frames. However, in the training opt file, we can get an error after modifying datasets:train:dataroot_GT and dataroot_LQ and datasets:val:dataroot_GT and dataroot_LQ:

`Traceback (most recent call last):`
`    File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/train.py", line 291, in <module>`
`        main()`
`    File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/train.py", line 137, in main`
`        train_set = create_dataset(dataset_opt)`
`    File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/data/__init__.py", line 42, in create_dataset`
`        dataset = D(dataset_opt)`
`    File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/data/Vimeo90K_dataset.py", line 72, in __init__`
`        self.paths_GT = pickle.load(open(opt['cache_keys'], 'rb'))['keys']`
`TypeError: list indices must be integers or slices, not str`

Is there anything I should pay extra attention to if I want to retrain on my own data? And is it feasible to retrain on my data set directly with the pre-training model "RDVR-H265-Stage2-Step2.pth"?

**Comment by 5ofwind** [comment]
Hi Mesks. Did you check your pkl file with the following code?

import pickle
f=open('name.pkl','rb')
data=pickle.load(f)
print(data)
print(len(data))

It is needed to check that the format of your pkl is the same as "Vimeo90K_train_keys.pkl". You should generate a new pkl file following the format of "Vimeo90K_train_keys.pkl" for your own dataset by modifying the pkl generation code. Did you use two subfolders for different sequences in your dataset? Please follow the settings in Vimeo90K dataset in which there are two subfolders (for example, "00096/0001/") before getting the png images. Another way is to modify the "Vimeo90K_dataset.py" file.

It is feasible to retrain on your dataset directly with the pre-trained model "RDVR-H265-Stage2-Step2.pth". However, maybe it is better to retrain our stage 1 model on your dataset first.

<img width="1280" alt="微信图片_20241111143201" src="https://github.com/user-attachments/assets/c534db8e-1d1b-49fd-8232-f742a4511614">
<img width="1280" alt="微信图片_20241111143205" src="https://github.com/user-attachments/assets/d0a1779e-9605-4cb4-8a50-ea6670bfe349">

**Comment by Mesks** [comment]
Well... I have seen a lot of fixed variable values in the code, it seems that the training code is only suitable for vimeo90K, other resolutions, file names, file storage formats are not supported...

**Comment by 5ofwind** [comment]
For different datasets, the format of the folders and files are different. You need to follow the codes and write new codes for new datasets. Another way is to strictly follow the format of Vimeo90K to form your own data.

For a fair comparison with other methods such as CLSA, MIMO-VRN and SelfC, we only adopt Vimeo90K training dataset for training. Our data preparation codes are based on those of MIMO-VRN (which is based on BasicSR). For video super-resolution, the most commonly used training datasets are Vimeo90K and REDS. You can see separate python files for Vimeo90K and REDS in the codes of EDVR and BasicVSR++. Since the format is complex in each dataset and the training dataset is usually fixed, it is common to use different files for different training datasets.

**Comment by 5ofwind** [comment]
For different datasets, the formats of the folders and files are different. You need to follow the codes and write new codes for new datasets. Another way is to strictly follow the format of Vimeo90K to form your own data.

For a fair comparison with other methods such as CLSA, MIMO-VRN and SelfC, we only adopt Vimeo90K training dataset for training. Our data preparation codes are based on those of MIMO-VRN (which is based on BasicSR). For video super-resolution, the most commonly used training datasets are Vimeo90K and REDS. You can see separate python files for Vimeo90K and REDS in the codes of EDVR and BasicVSR++. Since the format is complex in each dataset and the training dataset is usually fixed, it is common to use different files for different training datasets.

**Comment by 5ofwind** [comment]
For different datasets, the formats of the folders and files are different. You need to follow the codes and write new codes for new datasets. Another way is to strictly follow the format of Vimeo90K to form your own data.

For a fair comparison with other methods such as CLSA, MIMO-VRN and SelfC, we only adopt Vimeo90K training dataset for training. Our data preparation codes are based on those of MIMO-VRN (which is based on BasicSR). For video super-resolution, the most commonly used training datasets are Vimeo90K and REDS. You can see separate python files for Vimeo90K and REDS in the codes of EDVR and BasicVSR++. Since the format is complex in each dataset and the training dataset is usually fixed, it is common to use different files for different training datasets.

**Comment by Mesks** [comment]
I reconstructed the data according to Viemo90K, but for fairness, I still used different resolutions as the retrained data, so I also modified part of the code of Vimeo90K_dataset.py. It is not clear whether other errors would be caused.

At the same time, I found the following errors in the process of retraining, which seemed to be the gradient calculation error caused by the in-situ reconstruction of the tensor. Just like the question I raised in [another question](https://github.com/5ofwind/RDVR/issues/2) last time, why there are a lot of clone, I think it is to solve this problem. But in RDVR-H265-Stage2-Step2/codes/train.py debug appears again, if you are experienced with this please let me know, thank you very much.

Traceback (most recent call last):
File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/train.py", line 293,  in <module>
main()
File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/train.py", line 190,  in main
model.optimize_parameters()
File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/models/VRN_model.py",  line 269, in optimize_parameters
loss.backward()
The File "/ share3 / home/queshicheng/anaconda3 / envs/RDVR/lib/python3.10 / site - packages/torch / _tensor py", line 488, in backward
torch.autograd.backward(
The File "/ share3 / home/queshicheng/anaconda3 / envs/RDVR/lib/python3.10 / site - packages/torch/autograd/set py", line 197, in backward
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation:  [torch.cuda. FloatTensor [4, 3, 144, 144]], which is output 0 of AsStridedBackward0, is at version 2;   expected version 0 instead.  Hint:  the backtrace further above shows the operation that failed to compute its gradient.  The variable in question was  changed in there or anywhere later.  Good luck!

**Comment by Mesks** [comment]
> For different datasets, the formats of the folders and files are different. You need to follow the codes and write new codes for new datasets. Another way is to strictly follow the format of Vimeo90K to form your own data.
> 
> For a fair comparison with other methods such as CLSA, MIMO-VRN and SelfC, we only adopt Vimeo90K training dataset for training. Our data preparation codes are based on those of MIMO-VRN (which is based on BasicSR). For video super-resolution, the most commonly used training datasets are Vimeo90K and REDS. You can see separate python files for Vimeo90K and REDS in the codes of EDVR and BasicVSR++. Since the format is complex in each dataset and the training dataset is usually fixed, it is common to use different files for different training datasets.

I reconstructed the data according to Viemo90K, but for fairness, I still used different resolutions as the retrained data, so I also modified part of the code of Vimeo90K_dataset.py. It is not clear whether other errors would be caused.

At the same time, I found the following errors in the process of retraining, which seemed to be the gradient calculation error caused by the in-situ reconstruction of the tensor. Just like the question I raised in https://github.com/5ofwind/RDVR/issues/2 last time, why there are a lot of clone, I think it is to solve this problem. But in RDVR-H265-Stage2-Step2/codes/train.py debug appears again, if you are experienced with this please let me know, thank you very much.

![image](https://github.com/user-attachments/assets/c464ee44-ac02-4232-ac26-b781ad59c879)

Traceback (most recent call last):
File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/train.py", line 293, in
main()
File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/train.py", line 190, in main
model.optimize_parameters()
File "/share3/home/queshicheng/__Workbanch/RDVR/RDVR-main/RDVR-H265/RDVR-H265-Stage2-Step2/codes/models/VRN_model.py", line 269, in optimize_parameters
loss.backward()
The File "/ share3 / home/queshicheng/anaconda3 / envs/RDVR/lib/python3.10 / site - packages/torch / _tensor py", line 488, in backward
torch.autograd.backward(
The File "/ share3 / home/queshicheng/anaconda3 / envs/RDVR/lib/python3.10 / site - packages/torch/autograd/set py", line 197, in backward
Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda. FloatTensor [4, 3, 144, 144]], which is output 0 of AsStridedBackward0, is at version 2; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by 5ofwind** [comment]
We haven't met that problem. I think you can use debugging techniques to find out which line caused the problem. Best regards.

**Comment by 5ofwind** [comment]
Hi. Recently I met the same problem. I find that this is caused by the different PyTorch versions. Previously I use 1.10.0. Now I use 2.4.1. I find that by replacing the corresponding code in Inv_arch.py, the problem can be solved. The code is as follows.

			if not rev:
				out_y = self.irn(x, rev)
				return out_y
			else:
				y, _ = x #x, _
				out_z = self.pm(y)
				out_x = self.irn(torch.cat([y, out_z], dim=1), rev)
				out_x0=out_x.clone()
				out_z=[]
				y=[]
				                
				out_x=out_x.clone()
				out_x23=out_x[:,3:9,:,:].clone()
				out_x2=out_x[:,3:6,:,:].clone()
				out_x43=torch.cat([out_x[:,9:12,:,:],out_x[:,6:9,:,:]],1).clone()
				out_x4=out_x[:,9:12,:,:].clone()
				
				out_x2=(self.pm2(out_x23)+out_x2).clone()
				out_x[:,3:6,:,:]=out_x2.clone()
				out_x4=(self.pm2(out_x43)+out_x4).clone()
				out_x[:,9:12,:,:]=out_x4.clone()
				
				out_x=out_x.clone()
				out_x12=out_x[:,0:6,:,:].clone()
				out_x1=out_x[:,0:3,:,:].clone()
				out_x54=torch.cat([out_x[:,12:15,:,:],out_x[:,9:12,:,:]],1).clone()
				out_x5=out_x[:,12:15,:,:].clone()
				
				out_x1=(self.pm2(out_x12)+out_x1).clone()
				out_x5=(self.pm2(out_x54)+out_x5).clone()
				out_x[:,0:3,:,:]=out_x1.clone()
				out_x[:,12:15,:,:]=out_x5.clone()
				
				return out_x, out_z, out_x0
